<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-BR47O9U" failures="1" tests="1" name="Test(failed)(failed)" time="0.101" errors="0" timestamp="2023-09-26T16:48:47 EDT">
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase2" time="0.028">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at dineshpackageinterview.Runfailedtestcase.testcase2(Runfailedtestcase.java:14)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase1" time="0.0">
    <ignored/>
  </testcase> <!-- testcase1 -->
</testsuite> <!-- Test(failed)(failed) -->
