<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BR47O9U" failures="2" tests="8" name="Test(failed)" time="0.103" errors="0" timestamp="2023-09-26T17:40:07 EDT">
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase1" time="0.024">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase2" time="0.024">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase1" time="0.001">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase2" time="0.001">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase1" time="0.003">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase2" time="0.001">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at dineshpackageinterview.Runfailedtestcase.testcase1(Runfailedtestcase.java:11)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="dineshpackageinterview.Runfailedtestcase" name="testcase2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at dineshpackageinterview.Runfailedtestcase.testcase2(Runfailedtestcase.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- Test(failed) -->
